<header class="header">
    <div class="header__title-row">
        <h1 class="header__title"><a href="/" class="header__title-link" title="Back to Home" rel="home"><?= $siteConfig->title ?></a></h1>
        <button class="header__nav-button">
            <svg height="32px" class="header__nav-icon" style="enable-background:new 0 0 32 32;" version="1.1" viewBox="0 0 32 32" width="32px" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                <path d="M4,10h24c1.104,0,2-0.896,2-2s-0.896-2-2-2H4C2.896,6,2,6.896,2,8S2.896,10,4,10z M28,14H4c-1.104,0-2,0.896-2,2  s0.896,2,2,2h24c1.104,0,2-0.896,2-2S29.104,14,28,14z M28,22H4c-1.104,0-2,0.896-2,2s0.896,2,2,2h24c1.104,0,2-0.896,2-2  S29.104,22,28,22z" /></svg>
        </button>
    </div>
    <div class="header__blackbanner">
        <h2 class="header__tagline"><?= $siteConfig->tagline ?></h2>
        <img class="header__logo" src="<?= $siteConfig->base_url ?>/tpl-img/alex.svg" width="180px" height="172px">
    </div>
</header>
<nav class="main-nav">
  <div class="main-nav__content">
    <?= $generatedMenus['main'] ?>
    <?= $generatedMenus['social'] ?>
  </div>
</nav>
