<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<title><?= $config->title ?> – <?= $config->tagline; ?></title>
<meta name="description" content="<?= $config->desciption; ?>">

<link rel="canonical" href="<?= $config->base_url . '/' . $slug ?>.html" />
<link rel="stylesheet" href="<?= $config->base_url ?>/css/styles.css">
<script src="<?= $config->base_url ?>/js/main.js" defer></script>

<meta property="og:type" content="article" />
<meta property="og:title" content="<?= $config->title ?> – <?= $config->tagline; ?>" />
<meta property="og:description" content="" />
<meta property="og:url" content="" />

<meta property="og:site_name" content="<?= $config->title ?>" />
<meta name="twitter:title" content="<?= $config->title ?> – <?= $config->tagline; ?>">
<meta name="twitter:description" content="<?= $config->desciption; ?>">

<meta name="twitter:site" content="<?= $config->twitter_handle ?>">
<meta name="twitter:creator" content="<?= $config->twitter_handle ?>">
