<!DOCTYPE html>
<html lang="<?= $config->language ?>">

<head>
  <?php include 'partials/head-index.phtml' ?>
</head>

<body>
  <?php include 'partials/header.phtml' ?>
  
  <h1><?=ucfirst($config->tag_path) ?>: <?=implode('-', array_map('ucfirst', explode('-', $slug))); ?></h1>
  <?php if($snippet !== null) print $snippet->get('content') ?>

  <?php
    foreach ($entities as $entity) :
      include __DIR__ . '/partials/article.phtml';
    endforeach;
  ?>

  <?php include 'partials/footer.phtml' ?>

</body>

</html>
